
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2018-02-07 00:46:41.166102459 -0800 PST m=+0.000409656

package gosu

import (
	"encoding/binary"
	"io"
)

func (this *Byte) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Byte) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Short) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Short) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Int) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Int) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Long) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Long) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Single) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Single) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Double) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Double) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *Boolean) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *Boolean) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *DateTime) UnmarshalBinary(buf io.Reader) error {
	return binary.Read(buf, binary.LittleEndian, this)
}

func (this *DateTime) MarshalBinary(buf io.Writer) error {
	return binary.Write(buf, binary.LittleEndian, this)
}

func (this *OsuDb) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *OsuDb) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *IntDoublePair) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *IntDoublePair) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *TimingPoint) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *TimingPoint) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *BeatMap) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *BeatMap) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *CollectionDb) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *CollectionDb) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *CollectionDbElement) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *CollectionDbElement) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *ScoresDb) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *ScoresDb) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *ScoresDbBeatMap) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *ScoresDbBeatMap) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *ScoresDbBeatMapScore) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *ScoresDbBeatMapScore) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *PresenceDb) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *PresenceDb) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}

func (this *PlayerPresence) UnmarshalBinary(buf io.Reader) error {
	return UnmarshalAny(this, buf)
}

func (this *PlayerPresence) MarshalBinary(buf io.Writer) error {
	return MarshalAny(this, buf)
}
